-- ------------------------------------------------------------------------------------------------------------------------------
-- GENERAL PURPOSE TABLES FOR BOOKINGS & DQ
-- ------------------------------------------------------------------------------------------------------------------------------

-- ------------------------------------------
-- TABLE OF OPPS AND ITS LATEST ITEMS
-- ------------------------------------------
DROP TABLE IF EXISTS T_OPP_QUOTES_OFFERS;
CREATE TABLE T_OPP_QUOTES_OFFERS (
  KEY ix_oppid (OPPID),
  KEY ix_offid (OFFID),
  KEY ix_qtid (QTID),
  KEY ix_assid (ADDID)
) DEFAULT CHARACTER SET UTF8
  AS 
  SELECT 
    OPP._ID OPPID, 
    OPP.FLOWS_SALESSTAGES_STATE_NAME FLOWSTATE, 
    OPP.EXTENSIONS_MASTER_CLIENTTHEATRE_VALUE_DISPLAYNAME THEATER,
    OPP.EXTENSIONS_MASTER_BATCHQUARTER_VALUE BATCHQUARTER,
    OPP.ISSUBORDINATE,
    OPP.AMOUNT_AMOUNT OPPAMT,
    OPP.TARGETAMOUNT_AMOUNT OPPTARAMT,
    QTR.RELNAME QTREL, 
    QTR.DESTKEY QTID, -- QT.AMOUNT_AMOUNT QTAMT,
    OFFR.SOURCEKEY OFFID, 
    OFF.AMOUNT_AMOUNT OFFAMT, 
    OFF.TARGETAMOUNT_AMOUNT OFFTARAMT,
    ASSR.DESTKEY ASSID, 
    ASS.AMOUNT_AMOUNT ASSAMT, 
    ASS.ENDDATE ASSENDDATE
  FROM APP_OPPORTUNITIES OPP
    LEFT OUTER JOIN RELATIONSHIPS QTR 
      ON OPP._ID = QTR.SOURCEKEY AND QTR.RELNAME in ('baseQuote', 'primaryQuote', 'latestQuote') AND QTR.SOURCETABLE = 'APP_OPPORTUNITIES'
    LEFT OUTER JOIN APP_QUOTES QT
      ON QTR.DESTKEY = QT._ID
    LEFT OUTER JOIN RELATIONSHIPS OFFR 
      ON QTR.DESTKEY = OFFR.DESTKEY AND OFFR.RELNAME = 'quote' AND OFFR.SOURCETABLE = 'APP_OFFERS'
    LEFT OUTER JOIN APP_OFFERS OFF 
      ON OFFR.DESTKEY = OFF._ID
    LEFT OUTER JOIN RELATIONSHIPS ASSR 
      ON OFFR.SOURCEKEY = ASSR.SOURCEKEY AND ASSR.RELNAME = 'predecessor' AND ASSR.SOURCETABLE = 'APP_OFFERS'
    LEFT OUTER JOIN APP_ASSETS ASS ON 
      ASSR.DESTKEY = ASS._ID;

-- ------------------------------------------
-- HELPER TABLE TO GET SUBORDINATE AND MASTER OPP
-- ------------------------------------------
DROP TABLE IF EXISTS T_MASTER_SUB_OPP;
CREATE TABLE T_MASTER_SUB_OPP (
  KEY ix_leadoppid (LEADOPPID)
) DEFAULT CHARACTER SET UTF8
  AS 
  SELECT
    COALESCE(OPPR.DESTKEY, OPP._ID) LEADOPPID,
    OPP._ID MASTEROPPID, 
    OPPR.DESTKEY SUBOPPID
  FROM APP_OPPORTUNITIES OPP
    LEFT OUTER JOIN RELATIONSHIPS OPPR 
      ON OPP._ID = OPPR.SOURCEKEY AND OPPR.RELNAME = 'subordinateOpportunity' AND OPPR.SOURCETABLE = 'APP_OPPORTUNITIES'
  WHERE OPP.ISSUBORDINATE <> 'true';

-- ------------------------------------------
-- HELPER TABLE TO GET THE MOST ACTIVE QUOTE
-- ------------------------------------------
DROP TABLE IF EXISTS T_ACTIVE_QUOTE;
CREATE TABLE T_ACTIVE_QUOTE (
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OPP._ID as OPPID, 
    COALESCE(PQ.DESTKEY, BQ.DESTKEY) QTID, 
    COALESCE(PQ.RELNAME, BQ.RELNAME) QTREL
  FROM APP_OPPORTUNITIES OPP 
    LEFT OUTER JOIN RELATIONSHIPS PQ 
      ON PQ.RELNAME = 'primaryQuote' AND OPP._ID = PQ.SOURCEKEY AND PQ.SOURCETABLE = 'APP_OPPORTUNITIES'
    LEFT OUTER JOIN RELATIONSHIPS BQ 
      ON BQ.RELNAME = 'baseQuote' AND OPP._ID = BQ.SOURCEKEY AND BQ.SOURCETABLE = 'APP_OPPORTUNITIES';

-- ------------------------------------------
-- HELPER TABLE TO GET THE INITIAL QUOTE
-- ------------------------------------------
DROP TABLE IF EXISTS T_INITIAL_QUOTE;
CREATE TABLE T_INITIAL_QUOTE (
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OPP._ID as OPPID, 
    BQ.DESTKEY QTID,
    BQ.RELNAME QTREL
  FROM APP_OPPORTUNITIES OPP 
    LEFT OUTER JOIN RELATIONSHIPS BQ 
      ON BQ.RELNAME = 'baseQuote' AND OPP._ID = BQ.SOURCEKEY AND BQ.SOURCETABLE = 'APP_OPPORTUNITIES';

-- ------------------------------------------
-- HELPER TABLE TO GET THE MOST ACTIVE OFFERS
-- ------------------------------------------
DROP TABLE IF EXISTS T_ACTIVE_OFFERS;
CREATE TABLE T_ACTIVE_OFFERS (
  KEY ix_offid (OFFID),
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OFF._ID AS OFFID,
    VAQ.OPPID,
    VAQ.QTREL,
    VAQ.QTID
  FROM 
    APP_OFFERS OFF, 
    RELATIONSHIPS OQ, 
    T_ACTIVE_QUOTE VAQ,
    T_MASTER_SUB_OPP MSO
  WHERE 
    VAQ.OPPID = MSO.LEADOPPID
    AND OQ.DESTKEY = VAQ.QTID
    AND OFF._ID = OQ.SOURCEKEY AND OQ.RELNAME = 'quote' AND OQ.SOURCETABLE = 'APP_OFFERS';

-- ------------------------------------------
-- HELPER TABLE TO GET THE BASE OFFERS
-- TO BE USED FOR SPLIT OFFER FUNCTIONS
-- ------------------------------------------
DROP TABLE IF EXISTS T_BASE_OFFERS;
CREATE TABLE T_BASE_OFFERS (
  KEY ix_offid (OFFID),
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OFF._ID AS OFFID,
    VAQ.OPPID,
    VAQ.QTREL,
    VAQ.QTID
  FROM 
    APP_OFFERS OFF, 
    RELATIONSHIPS OQ, 
    T_INITIAL_QUOTE VAQ 
  WHERE 
    OFF._ID = OQ.SOURCEKEY AND OQ.RELNAME = 'quote' AND OQ.SOURCETABLE = 'APP_OFFERS' 
    AND OQ.DESTKEY = VAQ.QTID;
