SET NAMES 'utf8';

-- ------------------------------------------------------------------------------------------------------------------------------
-- SIMPLIFIED VIEWS FOR DQ
-- ------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW SERVICE_ASSETS AS
  SELECT 
    *
  FROM 
    APP_ASSETS
  WHERE 
    TYPE = 'app.asset/service';

CREATE OR REPLACE VIEW COVERED_ASSETS AS
  SELECT 
    *
  FROM 
    APP_ASSETS
  WHERE 
    TYPE = 'app.asset/covered';

-- ------------------------------------------------------------------------------------------------------------------------------
-- GOODDATA VIEWS
-- ------------------------------------------------------------------------------------------------------------------------------

-- ------------------------------------------
-- GOODDATA OPPORTUNITIES VIEW
CREATE OR REPLACE VIEW GDV_OPPORTUNITIES AS
  SELECT 
    OPP._ID AS OpportunityPK,
    OPP.TARGETAMOUNT_NORMALIZEDAMOUNT_AMOUNT AS OpportunityRenewalAmountUSD,
    OPP.AMOUNT_NORMALIZEDAMOUNT_AMOUNT AS OpportunityTransactionAmountUSD,
    OPP.TARGETAMOUNT_AMOUNT AS OpportunityRenewalAmountLocal,
    OPP.AMOUNT_AMOUNT AS OpportunityTransactionAmountLocal,
    OPP.SYSTEMPROPERTIES_TENANT AS Tenant,
    OPP.COMMITLEVEL_NAME AS CommitLevel,
    OPP.SYSTEMPROPERTIES_CREATEDBY AS CreatedBy,
    OPP.SYSTEMPROPERTIES_LASTMODIFIEDBY AS ModifiedBy,
    OPP.FLOWS_SALESSTAGES_STATE_NAME AS SalesStage,
    OPP.DISPLAYNAME AS OpportunityName,
    OPP.EXTENSIONS_MASTER_DIRECTCHANNEL_VALUE_DISPLAYNAME AS DirectChannel,
    OPP.TARGETAMOUNT_CODE_NAME AS LocalRenewalCurrency,
    OPP.AMOUNT_CODE_NAME AS LocalTransactionCurrency,
    OPP.SYSTEMPROPERTIES_CREATEDON AS CreatedOnDate,
    OPP.TARGETDATE AS EarliestExistingEndDate,
    OPP.TARGETDATE AS EstimatedCloseDate,
    OPP.SYSTEMPROPERTIES_MODIFIEDON AS ModifiedDate,
    OPP.RESOLUTIONDATE AS ResolutionDate,
    OPP.EXTENSIONS_MASTER_CLIENTTHEATRE_VALUE_DISPLAYNAME AS ClientTheatre,
    OPP.EXTENSIONS_MASTER_BUSINESSLINE_VALUE_DISPLAYNAME AS BusinessLine,
    OPP.EXTENSIONS_MASTER_CLIENTREGION_VALUE_DISPLAYNAME AS ClientRegion,
    OPP.EXTENSIONS_MASTER_CLIENTTERRITORY_VALUE_DISPLAYNAME AS ClientTerritory,
    OPP.EXTENSIONS_MASTER_COUNTRY_VALUE_DISPLAYNAME AS Country,
    IRR.DESTNAME AS ExistingReseller,
    CR.DESTNAME AS Customer,
    (SELECT MIN(SR.DESTNAME) FROM RELATIONSHIPS SR WHERE SR.SOURCEKEY = OPP._ID AND SR.RELNAME = 'salesRep' AND SR.SOURCETABLE = 'APP_OPPORTUNITIES') AS SalesRep, -- ONLY GET ONE
    OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATECONTACTED_CHANGEDATE AS FirstContactDate,
    LEAST(
      CASE 
        WHEN OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTEDELIVERED_CHANGEDATE = '0000-00-00 00:00:00' THEN '2050-12-31 00:00:00' 
        ELSE OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTEDELIVERED_CHANGEDATE 
       END, 
       CASE 
        WHEN OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTECOMPLETED_CHANGEDATE = '0000-00-00 00:00:00' THEN '2050-12-31 00:00:00' 
        ELSE OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTECOMPLETED_CHANGEDATE
       END,
       CASE 
        WHEN OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTEREQUESTED_CHANGEDATE = '0000-00-00 00:00:00' THEN '2050-12-31 00:00:00' 
        ELSE OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATEQUOTEREQUESTED_CHANGEDATE 
       END) AS FirstQuoteDate,
    OPP.FLOWS_SALESSTAGES_TRANSITIONS_TOSTATECLOSEDSALE_CHANGEDATE AS BookingDate,
    NULL AS OpportunityType,
    BR.DESTKEY AS BookingPK,
    PR.DESTKEY AS QuotePK,
    IDR.DESTNAME AS ExistingDistributor,
    (SELECT MIN(DR.DESTNAME) FROM RELATIONSHIPS DR WHERE DR.SOURCEKEY = OPP._ID AND DR.RELNAME = 'distributor' AND DR.SOURCETABLE = 'APP_OPPORTUNITIES') AS NewDistributor, -- ONLY GET ONE
    RR.DESTNAME AS NewReseller,
    OPP.EXTENSIONS_MASTER_EARLIESTNEWSTARTDATE_VALUE AS EarliestNewStartDate,
    OPP.EXTENSIONS_MASTER_LATESTNEWENDDATE_VALUE AS LatestNewEndDate,
    (CASE 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME in ('closedSale','houseaccount','noservice') THEN OPP.RESOLUTIONDATE 
      ELSE coalesce(OPP.EXTENSIONS_MASTER_FORECASTEDCLOSEDATE_VALUE, OPP.SYSTEMPROPERTIES_MODIFIEDON) 
     END) AS TransactionDate,
    (CASE  
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'notContacted' THEN 'a. Not Contacted' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'contacted' THEN 'b. Contacted' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'quoteRequested' THEN 'c. Quote Requested' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'quoteCompleted' THEN 'd. Quote Completed' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'quoteDelivered' THEN 'e. Quote Delivered' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'customerCommitment' THEN 'f. Customer Commitment' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'poReceived' THEN 'g. PO Received' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'closedSale' THEN 'h. Closed Sale' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'noService' THEN 'i. No Service' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'houseAccount' THEN 'j. House Account' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'consolidated' THEN 'k. Consolidated' 
      WHEN OPP.FLOWS_SALESSTAGES_STATE_NAME = 'transitioned' THEN 'l. Transitioned' 
      ELSE 'XX. Error - Unknown Sales Stage' 
     END) AS SalesStageOrder,
    OPP.EXTENSIONS_MASTER_TARGETPERIOD_VALUE_NAME AS SellingPeriod,
    '$OPPORTUNITIES_CUSTOMFIELD1$' AS CUSTOMFIELD1,
    '$OPPORTUNITIES_CUSTOMFIELD2$' AS CUSTOMFIELD2,
    '$OPPORTUNITIES_CUSTOMFIELD3$' AS CUSTOMFIELD3,
    '$OPPORTUNITIES_CUSTOMFIELD4$' AS CUSTOMFIELD4,
    '$OPPORTUNITIES_CUSTOMFIELD5$' AS CUSTOMFIELD5,
    '$OPPORTUNITIES_CUSTOMFIELD6$' AS CUSTOMFIELD6,
    '$OPPORTUNITIES_CUSTOMFIELD7$' AS CUSTOMFIELD7,
    '$OPPORTUNITIES_CUSTOMFIELD8$' AS CUSTOMFIELD8,
    '$OPPORTUNITIES_CUSTOMFIELD9$' AS CUSTOMFIELD9,
    '$OPPORTUNITIES_CUSTOMFIELD10$' AS CUSTOMFIELD10,
    '$OPPORTUNITIES_CUSTOMFIELD11$' AS CUSTOMFIELD11,
    '$OPPORTUNITIES_CUSTOMFIELD12$' AS CUSTOMFIELD12,
    '$OPPORTUNITIES_CUSTOMFIELD13$' AS CUSTOMFIELD13,
    '$OPPORTUNITIES_CUSTOMFIELD14$' AS CUSTOMFIELD14,
    '$OPPORTUNITIES_CUSTOMFIELD15$' AS CUSTOMFIELD15,
    '$OPPORTUNITIES_CUSTOMFIELD16$' AS CUSTOMFIELD16,
    '$OPPORTUNITIES_CUSTOMFIELD17$' AS CUSTOMFIELD17,
    '$OPPORTUNITIES_CUSTOMFIELD18$' AS CUSTOMFIELD18,
    '$OPPORTUNITIES_CUSTOMFIELD19$' AS CUSTOMFIELD19,
    '$OPPORTUNITIES_CUSTOMFIELD20$' AS CUSTOMFIELD20,
    '$OPPORTUNITIES_CUSTOMFACT1$' AS CUSTOMFACT1,
    '$OPPORTUNITIES_CUSTOMFACT2$' AS CUSTOMFACT2,
    '$OPPORTUNITIES_CUSTOMFACT3$' AS CUSTOMFACT3,
    '$OPPORTUNITIES_CUSTOMFACT4$' AS CUSTOMFACT4,
    '$OPPORTUNITIES_CUSTOMFACT5$' AS CUSTOMFACT5, 
    '$OPPORTUNITIES_CUSTOMDATE1$' AS CUSTOMDATE1 
  FROM APP_OPPORTUNITIES OPP
    LEFT OUTER JOIN RELATIONSHIPS CR 
      ON CR.SOURCEKEY = OPP._ID AND CR.SOURCETABLE = 'APP_OPPORTUNITIES' AND CR.RELNAME = 'customer'
    LEFT OUTER JOIN RELATIONSHIPS BR 
      ON BR.SOURCEKEY = OPP._ID AND BR.SOURCETABLE = 'APP_OPPORTUNITIES' AND BR.RELNAME = 'booking'
    LEFT OUTER JOIN RELATIONSHIPS PR 
      ON PR.SOURCEKEY = OPP._ID AND PR.SOURCETABLE = 'APP_OPPORTUNITIES' AND PR.RELNAME = 'primaryQuote'
    LEFT OUTER JOIN RELATIONSHIPS RR
      ON RR.SOURCEKEY = OPP._ID AND RR.SOURCETABLE = 'APP_OPPORTUNITIES' AND RR.RELNAME = 'primaryReseller'
    LEFT OUTER JOIN RELATIONSHIPS IRR 
      ON IRR.SOURCEKEY = OPP._ID AND IRR.SOURCETABLE = 'APP_OPPORTUNITIES' AND IRR.RELNAME = 'incumbentReseller'
    LEFT OUTER JOIN RELATIONSHIPS IDR
      ON IDR.SOURCEKEY = OPP._ID AND IDR.SOURCETABLE = 'APP_OPPORTUNITIES' AND IDR.RELNAME = 'incumbentDistributor'
  WHERE OPP.ISSUBORDINATE = 'false';
-- ------------------------------------------

-- ------------------------------------------
-- GOODDATA OFFERS VIEW
CREATE OR REPLACE VIEW GDV_OFFERS AS 
  SELECT 
    OFF._ID AS OfferPK,
    OFF.TARGETAMOUNT_NORMALIZEDAMOUNT_AMOUNT AS OfferRenewalAmountUSD,
    OFF.AMOUNT_NORMALIZEDAMOUNT_AMOUNT AS OfferTransactionAmountUSD,
    OFF.TARGETAMOUNT_AMOUNT AS OfferRenewalAmountLocal,
    OFF.AMOUNT_AMOUNT AS OfferTransactionAmountLocal,
    OFF.SYSTEMPROPERTIES_TENANT AS Tenant,
    OFF.EXTENSIONS_MASTER_BATCHTYPE_VALUE_DISPLAYNAME AS BatchType,
    OFF.SYSTEMPROPERTIES_CREATEDBY AS CreatedBy,
    OFF.SYSTEMPROPERTIES_LASTMODIFIEDBY AS ModifiedBy,
    OFF.RESULTREASON_NAME AS ResultReason,
    AR.DESTKEY AS AssetPK,
    QR.DESTKEY AS QuotePK,
    PR.DESTKEY AS NewServiceProduct,
    OFF.TARGETAMOUNT_CODE_NAME AS LocalRenewalCurrency,
    OFF.AMOUNT_CODE_NAME AS LocalTransactionCurrency,
    OFF.SYSTEMPROPERTIES_CREATEDON AS CreatedOnDate,
    OFF.SYSTEMPROPERTIES_MODIFIEDON AS ModifiedDate,
    OFF.STARTDATE AS NewStartDate,
    OFF.ENDDATE AS NewEndDate,
    NULL AS SalesStage,
    '$OFFERS_CUSTOMFIELD1$' AS CUSTOMFIELD1,
    '$OFFERS_CUSTOMFIELD2$' AS CUSTOMFIELD2,
    '$OFFERS_CUSTOMFIELD3$' AS CUSTOMFIELD3,
    '$OFFERS_CUSTOMFIELD4$' AS CUSTOMFIELD4,
    '$OFFERS_CUSTOMFIELD5$' AS CUSTOMFIELD5,
    '$OFFERS_CUSTOMFIELD6$' AS CUSTOMFIELD6,
    '$OFFERS_CUSTOMFIELD7$' AS CUSTOMFIELD7,
    '$OFFERS_CUSTOMFIELD8$' AS CUSTOMFIELD8,
    '$OFFERS_CUSTOMFIELD9$' AS CUSTOMFIELD9,
    '$OFFERS_CUSTOMFIELD10$' AS CUSTOMFIELD10,
    '$OFFERS_CUSTOMFIELD11$' AS CUSTOMFIELD11,
    '$OFFERS_CUSTOMFIELD12$' AS CUSTOMFIELD12,
    '$OFFERS_CUSTOMFIELD13$' AS CUSTOMFIELD13,
    '$OFFERS_CUSTOMFIELD14$' AS CUSTOMFIELD14,
    '$OFFERS_CUSTOMFIELD15$' AS CUSTOMFIELD15,
    '$OFFERS_CUSTOMFIELD16$' AS CUSTOMFIELD16,
    '$OFFERS_CUSTOMFIELD17$' AS CUSTOMFIELD17,
    '$OFFERS_CUSTOMFIELD18$' AS CUSTOMFIELD18,
    '$OFFERS_CUSTOMFIELD19$' AS CUSTOMFIELD19,
    '$OFFERS_CUSTOMFIELD20$' AS CUSTOMFIELD20,
    '$OFFERS_CUSTOMFACT1$' AS CUSTOMFACT1,
    '$OFFERS_CUSTOMFACT2$' AS CUSTOMFACT2,
    '$OFFERS_CUSTOMFACT3$' AS CUSTOMFACT3,
    '$OFFERS_CUSTOMFACT4$' AS CUSTOMFACT4,
    '$OFFERS_CUSTOMFACT5$' AS CUSTOMFACT5, 
    '$OFFERS_CUSTOMDATE1$' AS CUSTOMDATE1 
  FROM APP_OFFERS OFF
    LEFT OUTER JOIN RELATIONSHIPS AR 
      ON AR.SOURCEKEY = OFF._ID AND AR.SOURCETABLE = 'APP_OFFERS' AND AR.RELNAME = 'predecessor'
    LEFT OUTER JOIN RELATIONSHIPS QR 
      ON QR.SOURCEKEY = OFF._ID AND QR.SOURCETABLE = 'APP_OFFERS' AND QR.RELNAME = 'quote'
    LEFT OUTER JOIN RELATIONSHIPS PR
      ON PR.SOURCEKEY = OFF._ID AND PR.SOURCETABLE = 'APP_OFFERS' AND PR.RELNAME = 'product';

-- ------------------------------------------

-- ------------------------------------------
-- GOODDATA QUOTES VIEW
CREATE OR REPLACE VIEW GDV_QUOTES AS 
  SELECT 
    QT._ID AS QuotePK,
    QT.SYSTEMPROPERTIES_TENANT AS Tenant,
    QT.DISPLAYNAME AS QuoteName,
    '$QUOTES_CUSTOMFIELD1$' AS CUSTOMFIELD1,
    '$QUOTES_CUSTOMFIELD2$' AS CUSTOMFIELD2,
    '$QUOTES_CUSTOMFIELD3$' AS CUSTOMFIELD3,
    '$QUOTES_CUSTOMFIELD4$' AS CUSTOMFIELD4,
    '$QUOTES_CUSTOMFIELD5$' AS CUSTOMFIELD5,
    '$QUOTES_CUSTOMFIELD6$' AS CUSTOMFIELD6,
    '$QUOTES_CUSTOMFIELD7$' AS CUSTOMFIELD7,
    '$QUOTES_CUSTOMFIELD8$' AS CUSTOMFIELD8,
    '$QUOTES_CUSTOMFIELD9$' AS CUSTOMFIELD9,
    '$QUOTES_CUSTOMFIELD10$' AS CUSTOMFIELD10,
    '$QUOTES_CUSTOMFIELD11$' AS CUSTOMFIELD11,
    '$QUOTES_CUSTOMFIELD12$' AS CUSTOMFIELD12,
    '$QUOTES_CUSTOMFIELD13$' AS CUSTOMFIELD13,
    '$QUOTES_CUSTOMFIELD14$' AS CUSTOMFIELD14,
    '$QUOTES_CUSTOMFIELD15$' AS CUSTOMFIELD15,
    '$QUOTES_CUSTOMFIELD16$' AS CUSTOMFIELD16,
    '$QUOTES_CUSTOMFIELD17$' AS CUSTOMFIELD17,
    '$QUOTES_CUSTOMFIELD18$' AS CUSTOMFIELD18,
    '$QUOTES_CUSTOMFIELD19$' AS CUSTOMFIELD19,
    '$QUOTES_CUSTOMFIELD20$' AS CUSTOMFIELD20,
    '$QUOTES_CUSTOMFACT1$' AS CUSTOMFACT1,
    '$QUOTES_CUSTOMFACT2$' AS CUSTOMFACT2,
    '$QUOTES_CUSTOMFACT3$' AS CUSTOMFACT3,
    '$QUOTES_CUSTOMFACT4$' AS CUSTOMFACT4,
    '$QUOTES_CUSTOMFACT5$' AS CUSTOMFACT5
  FROM APP_QUOTES QT;
-- ------------------------------------------

-- ------------------------------------------
-- GOODDATA VIEW FOR ASSETS
CREATE OR REPLACE VIEW GDV_ASSETS AS 
  SELECT 
    ASS._ID AS AssetPK,
    ASS.STARTDATE AS ExistingStartDate,
    ASS.ENDDATE AS ExistingEndDate,
    SPR.DESTNAME AS ExistingServiceProduct,
    NULL AS ExistingCoveredProduct,
    ASS.SYSTEMPROPERTIES_TENANT AS Tenant,
    '$ASSETS_CUSTOMFIELD1$' AS CUSTOMFIELD1,
    '$ASSETS_CUSTOMFIELD2$' AS CUSTOMFIELD2,
    '$ASSETS_CUSTOMFIELD3$' AS CUSTOMFIELD3,
    '$ASSETS_CUSTOMFIELD4$' AS CUSTOMFIELD4,
    '$ASSETS_CUSTOMFIELD5$' AS CUSTOMFIELD5,
    '$ASSETS_CUSTOMFIELD6$' AS CUSTOMFIELD6,
    '$ASSETS_CUSTOMFIELD7$' AS CUSTOMFIELD7,
    '$ASSETS_CUSTOMFIELD8$' AS CUSTOMFIELD8,
    '$ASSETS_CUSTOMFIELD9$' AS CUSTOMFIELD9,
    '$ASSETS_CUSTOMFIELD10$' AS CUSTOMFIELD10,
    '$ASSETS_CUSTOMFIELD11$' AS CUSTOMFIELD11,
    '$ASSETS_CUSTOMFIELD12$' AS CUSTOMFIELD12,
    '$ASSETS_CUSTOMFIELD13$' AS CUSTOMFIELD13,
    '$ASSETS_CUSTOMFIELD14$' AS CUSTOMFIELD14,
    '$ASSETS_CUSTOMFIELD15$' AS CUSTOMFIELD15,
    '$ASSETS_CUSTOMFIELD16$' AS CUSTOMFIELD16,
    '$ASSETS_CUSTOMFIELD17$' AS CUSTOMFIELD17,
    '$ASSETS_CUSTOMFIELD18$' AS CUSTOMFIELD18,
    '$ASSETS_CUSTOMFIELD19$' AS CUSTOMFIELD19,
    '$ASSETS_CUSTOMFIELD20$' AS CUSTOMFIELD20,
    '$ASSETS_CUSTOMFACT1$' AS CUSTOMFACT1,
    '$ASSETS_CUSTOMFACT2$' AS CUSTOMFACT2,
    '$ASSETS_CUSTOMFACT3$' AS CUSTOMFACT3,
    '$ASSETS_CUSTOMFACT4$' AS CUSTOMFACT4,
    '$ASSETS_CUSTOMFACT5$' AS CUSTOMFACT5 
  FROM APP_ASSETS ASS
    LEFT OUTER JOIN RELATIONSHIPS SPR 
      ON SPR.SOURCEKEY = ASS._ID AND SPR.SOURCETABLE = 'APP_ASSETS' AND SPR.RELNAME = 'product';
-- ------------------------------------------

-- ------------------------------------------
-- GOODDATA BOOKINGS VIEW
CREATE OR REPLACE VIEW GDV_BOOKINGS AS 
  SELECT 
    BOO._ID AS BookingPK,
    BOO.SYSTEMPROPERTIES_TENANT AS Tenant,
    BOO.SYSTEMPROPERTIES_CREATEDON AS ClientBookingDate,
    NULL AS AssetPK,
    '$BOOKINGS_CUSTOMFIELD1$' AS CUSTOMFIELD1,
    '$BOOKINGS_CUSTOMFIELD2$' AS CUSTOMFIELD2,
    '$BOOKINGS_CUSTOMFIELD3$' AS CUSTOMFIELD3,
    '$BOOKINGS_CUSTOMFIELD4$' AS CUSTOMFIELD4,
    '$BOOKINGS_CUSTOMFIELD5$' AS CUSTOMFIELD5,
    '$BOOKINGS_CUSTOMFIELD6$' AS CUSTOMFIELD6,
    '$BOOKINGS_CUSTOMFIELD7$' AS CUSTOMFIELD7,
    '$BOOKINGS_CUSTOMFIELD8$' AS CUSTOMFIELD8,
    '$BOOKINGS_CUSTOMFIELD9$' AS CUSTOMFIELD9,
    '$BOOKINGS_CUSTOMFIELD10$' AS CUSTOMFIELD10,
    '$BOOKINGS_CUSTOMFIELD11$' AS CUSTOMFIELD11,
    '$BOOKINGS_CUSTOMFIELD12$' AS CUSTOMFIELD12,
    '$BOOKINGS_CUSTOMFIELD13$' AS CUSTOMFIELD13,
    '$BOOKINGS_CUSTOMFIELD14$' AS CUSTOMFIELD14,
    '$BOOKINGS_CUSTOMFIELD15$' AS CUSTOMFIELD15,
    '$BOOKINGS_CUSTOMFIELD16$' AS CUSTOMFIELD16,
    '$BOOKINGS_CUSTOMFIELD17$' AS CUSTOMFIELD17,
    '$BOOKINGS_CUSTOMFIELD18$' AS CUSTOMFIELD18,
    '$BOOKINGS_CUSTOMFIELD19$' AS CUSTOMFIELD19,
    '$BOOKINGS_CUSTOMFIELD20$' AS CUSTOMFIELD20,
    '$BOOKINGS_CUSTOMFACT1$' AS CUSTOMFACT1,
    '$BOOKINGS_CUSTOMFACT2$' AS CUSTOMFACT2,
    '$BOOKINGS_CUSTOMFACT3$' AS CUSTOMFACT3,
    '$BOOKINGS_CUSTOMFACT4$' AS CUSTOMFACT4,
    '$BOOKINGS_CUSTOMFACT5$' AS CUSTOMFACT5 
  FROM APP_BOOKINGS BOO;
-- ------------------------------------------

-- ------------------------------------------
-- TABLE OF OPPS AND ITS LATEST ITEMS
-- ------------------------------------------
DROP TABLE IF EXISTS T_OPP_QUOTES_OFFERS;
select now(), ' ==Executing "CREATE TABLE T_OPP_QUOTES_OFFERS' from dual;
CREATE TABLE T_OPP_QUOTES_OFFERS (
  KEY ix_oppid (OPPID),
  KEY ix_offid (OFFID),
  KEY ix_qtid (QTID),
  KEY ix_assid (ASSID)
) DEFAULT CHARACTER SET UTF8
  AS 
  SELECT 
    OPP._ID OPPID, 
    OPP.FLOWS_SALESSTAGES_STATE_NAME FLOWSTATE, 
    OPP.EXTENSIONS_MASTER_CLIENTTHEATRE_VALUE_DISPLAYNAME THEATER,
    OPP.EXTENSIONS_MASTER_BATCHQUARTER_VALUE BATCHQUARTER,
    OPP.ISSUBORDINATE,
    OPP.AMOUNT_AMOUNT OPPAMT,
    OPP.TARGETAMOUNT_AMOUNT OPPTARAMT,
    QTR.RELNAME QTREL, 
    QTR.DESTKEY QTID, -- QT.AMOUNT_AMOUNT QTAMT,
    OFFR.SOURCEKEY OFFID, 
    OFF.AMOUNT_AMOUNT OFFAMT, 
    OFF.TARGETAMOUNT_AMOUNT OFFTARAMT,
    ASSR.DESTKEY ASSID, 
    ASS.AMOUNT_AMOUNT ASSAMT, 
    ASS.ENDDATE ASSENDDATE
  FROM APP_OPPORTUNITIES OPP
    LEFT OUTER JOIN RELATIONSHIPS QTR 
      ON OPP._ID = QTR.SOURCEKEY AND QTR.RELNAME in ('baseQuote', 'primaryQuote', 'latestQuote') AND QTR.SOURCETABLE = 'APP_OPPORTUNITIES'
    LEFT OUTER JOIN APP_QUOTES QT
      ON QTR.DESTKEY = QT._ID
    LEFT OUTER JOIN RELATIONSHIPS OFFR 
      ON QTR.DESTKEY = OFFR.DESTKEY AND OFFR.RELNAME = 'quote' AND OFFR.SOURCETABLE = 'APP_OFFERS'
    LEFT OUTER JOIN APP_OFFERS OFF 
      ON OFFR.DESTKEY = OFF._ID
    LEFT OUTER JOIN RELATIONSHIPS ASSR 
      ON OFFR.SOURCEKEY = ASSR.SOURCEKEY AND ASSR.RELNAME = 'predecessor' AND ASSR.SOURCETABLE = 'APP_OFFERS'
    LEFT OUTER JOIN APP_ASSETS ASS ON 
      ASSR.DESTKEY = ASS._ID;

-- ------------------------------------------
-- HELPER TABLE TO GET SUBORDINATE AND MASTER OPP
-- ------------------------------------------
DROP TABLE IF EXISTS T_MASTER_SUB_OPP;
select now(), ' ==Executing "CREATE TABLE T_MASTER_SUB_OPP' from dual;
CREATE TABLE T_MASTER_SUB_OPP (
  KEY ix_leadoppid (LEADOPPID)
) DEFAULT CHARACTER SET UTF8
  AS 
  SELECT
    COALESCE(OPPR.DESTKEY, OPP._ID) LEADOPPID,
    OPP._ID MASTEROPPID, 
    OPPR.DESTKEY SUBOPPID,
    OPPR.RELNAME
  FROM APP_OPPORTUNITIES OPP
    LEFT OUTER JOIN RELATIONSHIPS OPPR 
      ON OPP._ID = OPPR.SOURCEKEY AND (OPPR.RELNAME = 'subordinateOpportunity' OR OPPR.RELNAME = 'primaryOpportunity') AND OPPR.SOURCETABLE = 'APP_OPPORTUNITIES'
  WHERE OPP.ISSUBORDINATE <> 'true';

CREATE INDEX idx_mso_m on T_MASTER_SUB_OPP(MASTEROPPID);
CREATE INDEX idx_mso_s on T_MASTER_SUB_OPP(SUBOPPID);

-- ------------------------------------------
-- HELPER TABLE TO GET THE MOST ACTIVE QUOTE
-- ------------------------------------------
DROP TABLE IF EXISTS T_ACTIVE_QUOTE;
select now(), ' ==Executing "CREATE TABLE T_ACTIVE_QUOTE' from dual;
CREATE TABLE T_ACTIVE_QUOTE (
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OPP._ID as OPPID, 
    COALESCE(PQ.DESTKEY, BQ.DESTKEY) QTID, 
    COALESCE(PQ.RELNAME, BQ.RELNAME) QTREL
  FROM APP_OPPORTUNITIES OPP 
    LEFT OUTER JOIN RELATIONSHIPS PQ 
      ON PQ.RELNAME = 'primaryQuote' AND OPP._ID = PQ.SOURCEKEY AND PQ.SOURCETABLE = 'APP_OPPORTUNITIES' AND PQ.DESTKEY IN (select distinct _id from APP_QUOTES where lower(ISINVALID) <> 'true')
    LEFT OUTER JOIN RELATIONSHIPS BQ 
      ON BQ.RELNAME = 'baseQuote' AND OPP._ID = BQ.SOURCEKEY AND BQ.SOURCETABLE = 'APP_OPPORTUNITIES';

-- ------------------------------------------
-- HELPER TABLE TO GET THE INITIAL QUOTE
-- ------------------------------------------
DROP TABLE IF EXISTS T_INITIAL_QUOTE;
select now(), ' ==Executing "CREATE TABLE T_INITIAL_QUOTE' from dual;
CREATE TABLE T_INITIAL_QUOTE (
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OPP._ID as OPPID, 
    BQ.DESTKEY QTID,
    BQ.RELNAME QTREL
  FROM APP_OPPORTUNITIES OPP 
    LEFT OUTER JOIN RELATIONSHIPS BQ 
      ON BQ.RELNAME = 'baseQuote' AND OPP._ID = BQ.SOURCEKEY AND BQ.SOURCETABLE = 'APP_OPPORTUNITIES';

-- ------------------------------------------
-- HELPER TABLE TO GET THE MOST ACTIVE OFFERS
-- ------------------------------------------
DROP TABLE IF EXISTS T_ACTIVE_OFFERS;
select now(), ' ==Executing "CREATE TABLE T_ACTIVE_OFFERS' from dual;
CREATE TABLE T_ACTIVE_OFFERS (
  KEY ix_offid (OFFID),
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OFF._ID AS OFFID,
    VAQ.OPPID,
    VAQ.QTREL,
    VAQ.QTID
  FROM 
    APP_OFFERS OFF, 
    RELATIONSHIPS OQ, 
    T_ACTIVE_QUOTE VAQ,
    T_MASTER_SUB_OPP MSO
  WHERE 
    VAQ.OPPID = MSO.LEADOPPID
    AND OQ.DESTKEY = VAQ.QTID
    AND OFF._ID = OQ.SOURCEKEY AND OQ.RELNAME = 'quote' AND OQ.SOURCETABLE = 'APP_OFFERS';

-- ------------------------------------------
-- HELPER TABLE TO GET THE BASE OFFERS
-- TO BE USED FOR SPLIT OFFER FUNCTIONS
-- ------------------------------------------
DROP TABLE IF EXISTS T_BASE_OFFERS;
select now(), ' ==Executing "CREATE TABLE T_BASE_OFFERS' from dual;
CREATE TABLE T_BASE_OFFERS (
  KEY ix_offid (OFFID),
  KEY ix_oppid (OPPID),
  KEY ix_qtid (QTID)
) DEFAULT CHARACTER SET UTF8
  AS
  SELECT 
    OFF._ID AS OFFID,
    VAQ.OPPID,
    VAQ.QTREL,
    VAQ.QTID
  FROM 
    APP_OFFERS OFF, 
    RELATIONSHIPS OQ, 
    T_INITIAL_QUOTE VAQ 
  WHERE 
    OFF._ID = OQ.SOURCEKEY AND OQ.RELNAME = 'quote' AND OQ.SOURCETABLE = 'APP_OFFERS' 
    AND OQ.DESTKEY = VAQ.QTID;
select now(), ' ==Complete' from dual;

-- ------------------------------------------------------------------------------------------------------------------------------
-- GENERAL PURPOSE VIEWS FOR BOOKINGS & DQ
-- ------------------------------------------------------------------------------------------------------------------------------

-- ------------------------------------------
-- VIEW OF OPPS AND ITS LATEST ITEMS
-- ------------------------------------------
CREATE OR REPLACE VIEW V_OPP_QUOTES_OFFERS AS 
  SELECT 
    *
  FROM T_OPP_QUOTES_OFFERS;

-- ------------------------------------------
-- HELPER VW TO GET SUBORDINATE AND MASTER OPP
-- ------------------------------------------
CREATE OR REPLACE VIEW V_MASTER_SUB_OPP AS 
  SELECT
    *
  FROM T_MASTER_SUB_OPP;

-- ------------------------------------------
-- HELPER VW TO GET THE MOST ACTIVE QUOTE
-- ------------------------------------------
CREATE OR REPLACE VIEW V_ACTIVE_QUOTE AS
  SELECT 
    *
  FROM T_ACTIVE_QUOTE;

-- ------------------------------------------
-- HELPER VW TO GET THE INITIAL QUOTE
-- ------------------------------------------
CREATE OR REPLACE VIEW V_INITIAL_QUOTE AS
  SELECT 
    *
  FROM T_INITIAL_QUOTE;

-- ------------------------------------------
-- HELPER VW TO GET THE MOST ACTIVE OFFERS
-- ------------------------------------------
CREATE OR REPLACE VIEW V_ACTIVE_OFFERS AS
  SELECT 
    *
  FROM T_ACTIVE_OFFERS;

-- ------------------------------------------
-- HELPER VW TO GET THE BASE OFFERS
-- TO BE USED FOR SPLIT OFFER FUNCTIONS
-- ------------------------------------------
CREATE OR REPLACE VIEW V_BASE_OFFERS AS
  SELECT 
    *
  FROM T_BASE_OFFERS;

-- ------------------------------------------------------------------------------------------------------------------------------
-- GENERAL PURPOSE TABLES FOR BOOKINGS & DQ
-- ------------------------------------------------------------------------------------------------------------------------------
