#!/usr/bin/perl

use utf8;
use POSIX;

$fle = $ARGV[0];

if ( $fle eq "" ) {
	print "File name is empty\n";
	exit 1;
}

open(FILE, "<", $fle)
	or die "Error: Cannot open $fle";
$firstline = <FILE>;

close(FILE);

#
# Strip \r\n and make it upper case
#
$firstline =~ s/\r|\n//g;
$firstline = uc $firstline;

$fupper = uc $fle;
#
# Trim directory and the _yyyy_mm_dd.txt from the file name
#
if (rindex($fupper, "/") >=0) {
        $fupper = substr($fupper, rindex($fupper, "/") + 1);
}
$fupper = substr($fupper,0,length($fupper) - 15);

%refmap = ();
$refmap{"DELIVERY_OF_DAILY_ORDERS_ACTIVITY"} = 
"#AGREE_PO|AGREE_SO|AGREE_ACCNT_NAME|AGREE_LINE_SERVICE_PART_NUM|AGREE_LINE_SERVICE_PRODUCT|AGREE_LINE_PRODUCT_GROUP|AGREE_SHIP_ACCNT_NAME|INVOICE_DATE|INVOICE_NUM|SO_CURRENCY|SO_DATE|SO_EXT_NET_PRICE_USD|SO_EXT_NET_PRICE|DOC_CURR_CODE|LOC_CURR_CODE";
$refmap{"ENTITLEMENT_DAILY_ACTIVITY_RENEW"} = 
"#AGREE_ID|AGREE_NAME|AGREE_NUM|AGREE_PO|AGREE_SALES_REGION|THEATER|AGREE_SO|NO_OF_ASSET_ENTL_ON_LINE|AGREE_LINE_ID|AGREE_LINE_NUM|AGREE_LINE_PART_LIST|AGREE_LINE_PART_NET|AGREE_LINE_PART_NET_PER_ASSET|ANNUALIZED_VALUE|AGREE_LINE_QTY|AGREE_LINE_CURRENCY|MSRP|MKTG_NAME|DISCOUNT_CODE|BUNDLE_PART_TRNS|AGREE_LINE_SERVICE_PART_NUM|PIM_DESCRIPTION|ASSET_NUM|ASSET_ID|ASSET_PO_NUM|ASSET_SERIAL_NUM|ASSET_SERVICE_REGION|ASSET_SHIP_DATE|ASSET_SHIP_YEAR|ASSET_SO_NUM|ASSET_ADDRESS_1|ASSET_ADDRESS_2|ASSET_ADDRESS_ID|ASSET_CITY|ASSET_COUNTRY|ASSET_POSTAL|ASSET_STATE|ASSET_PART_NUM|ASSET_PRODUCT|ASSET_PRODUCT_DIVISION|ASSET_PRODUCT_GROUP|ASSET_MASTER_PRODUCT_GROUP|EOSL|ASSET_PRODUCT_ID|ASSET_PRODUCT_LINE|ENTL_CREATE_DATE|ENTL_DELIVERY_TYPE|ENTL_END_DATE|ENTL_BATCH_QUARTER|ENTL_ID|ENTL_NAME|ENTL_NET_PRICE_PER_ASSET|ENTL_NET_PRICE_PER_ASSET_USD|ENTL_SERVICE_TYPE|ENTL_ST_DATE|PREV_AGREE_ID|PREV_ENTL_END|PREV_ENTL_PO|PREV_ENTL_SRVC_PART_NUM|PREV_ENTITLEMENT_ID|SO_CURRENCY|SO_DATE|SO_EXT_NET_PRICE|SO_EXT_NET_PRICE_USD|AGREE_ACCNT_ID|AGREE_ACCNT_NAME|AGREE_MASTER_ACCNT_ID|AGREE_MSTR_ACCNT_NAME|AGREE_ACCNT_GAN|AGREE_ACCNT_ADDRESS_1|AGREE_ACCNT_ADDRESS_2|AGREE_ACCNT_ADDRESS_ID|AGREE_ACCNT_CITY|AGREE_ACCNT_COUNTRY|AGREE_ACCNT_POSTAL|AGREE_ACCNT_STATE|AGREE_ACCNT_CONTACT_EMAIL|AGREE_ACCNT_CONTACT_NAME|AGREE_ACCNT_CONTACT_PHONE|AGREE_ACCNT_PGS_CONTACT_EMAIL|AGREE_ACCNT_PGS_CONTACT_FIRST|AGREE_ACCNT_PGS_CONTACT_ID|AGREE_ACCNT_PGS_CONTACT_LAST|AGREE_ACCNT_PGS_CONTACT_PHONE|AGREE_END_CUST_ID|AGREE_END_CUST_MSTR_ID|AGREE_END_CUST_NAME|AGREE_END_CUST_MSTR_NAME|AGREE_END_CUST_ADDRESS_1|AGREE_END_CUST_ADDRESS_2|AGREE_END_CUST_ADDRESS_ID|AGREE_END_CUST_CITY|AGREE_END_CUST_COUNTRY|AGREE_END_CUST_POSTAL|AGREE_END_CUST_STATE|AGREE_END_CUST_CONTACT_EMAIL|AGREE_END_CUST_CONTACT_NAME|AGREE_END_CUST_CONTACT_PHONE|AGREE_END_CUST_PGS_CONTACT_EMAIL|AGREE_END_CUST_PGS_CONTACT_FIRST|AGREE_END_CUST_PGS_CONTACT_ID|AGREE_END_CUST_PGS_CONTACT_LAST|AGREE_END_CUST_PGS_CONTACT_PHONE|AGREE_RES_MASTER_ACCNT_ID|AGREE_RES_ACCNT_NAME|AGREE_RES_ACCT_MSTR_NAME|AGREE_RES_ID|AGREE_RES_ADDRESS_1|AGREE_RES_ADDRESS_2|AGREE_RES_ADDRESS_ID|AGREE_RES_CITY|AGREE_RES_COUNTRY|AGREE_RES_POSTAL|AGREE_RES_STATE|AGREE_RES_CONTACT_EMAIL|AGREE_RES_CONTAC_NAME|AGREE_RES_CONTACT_PHONE|AGREE_RES_PGS_CONTACT_EMAIL|AGREE_RES_PGS_CONTACT_FIRST|AGREE_RES_PGS_CONTACT_ID|AGREE_RES_PGS_CONTACT_LAST|AGREE_RES_PGS_CONTACT_PHONE|AGREE_SHIP_ACCNT_NAME|AGREE_SHIP_ID|AGREE_SHIP_ADDRESS_1|AGREE_SHIP_ADDRESS_2|AGREE_SHIP_ADDRESS_ID|AGREE_SHIP_CITY|AGREE_SHIP_COUNTRY|AGREE_SHIP_POSTAL|AGREE_SHIP_STATE|AGREE_SHIP_CONTACT_EMAIL|AGREE_SHIP_CONTACT_NAME|AGREE_SHIP_CONTACT_PHONE|AGREE_SHIP_PGS_CONTACT_EMAIL|AGREE_SHIP_PGS_CONTACT_FIRST|AGREE_SHIP_PGS_CONTACT_ID|AGREE_SHIP_PGS_CONTACT_LAST|AGREE_SHIP_PGS_CONTACT_PHONE|ASSET_OWNER_ACCNT_NAME|ASSET_OWNER_ID|ASSET_OWNER_ADDRESS_1|ASSET_OWNER_ADDRESS_2|ASSET_OWNER_ADDRESS_ID|ASSET_OWNER_CITY|ASSET_OWNER_COUNTRY|ASSET_OWNER_POSTAL|ASSET_OWNER_STATE|ASSET_CONTACT_EMAIL|ASSET_CONTACT_FIRST|ASSET_CONTACT_ID|ASSET_CONTACT_LAST|ASSET_CONTACT_PHONE|ASSET_STATUS|POLYCOM_TERRITORY|PORTAL_PRIMARY_AGREE_NAME|PORTAL_PRIMARY_AGREE_ID";
$refmap{"WEEKLY_DISASSOCIATED_ASSETS"} = 
"#INTEGRATION_ID|ASSET|ASSET_NUM|SERIAL_NUM|ENTITLEMENT|AGREEMENT|PRODUCT|AGREE_LINE_SERVICE_PART_NUM|OPERATION_CD|ASSET_DISASSOCIATION_DT|PROD_INT_ID|AGREEMENT_ITEM|AGREEMENT_VALID_FLG|AGREEMENT_ACCOUNT|ASSET_OWNER_ACCOUNT|ENTITLEMENT_START_DT|ENTITLEMENT_END_DT|AGREE_START_DT|AGREE_END_DT";
$refmap{"WEEKLY_UNINSTALL_ASSETS"} = 
"#ASSET_UNINSTALL_DATE|ASSET_NUMBER|ASSET_ID|ASSET_SHIP_DATE|ASSET_SERIAL_NUM|AGREE_ID|AGREE_LINE_ID|AGREE_LINE_SERVICE_PART_NUM|ENTL_ID|ENTL_END_DATE";

if ( exists $refmap{$fupper} ) {
	$refline = $refmap{$fupper};
	if ( $refline eq $firstline ) {
		print "Format matches for $fle\n";
		exit 0;
	} else {
		print "Format does not match for $fle\n";
		exit 1;
	}
} else {
	print "Format does not exist for $fle\n";
	exit 1;
}
