SELECT 
  SUM(TEMPO.OPV) 'Opp Past 12mo Value', 
  SUM(TEMPO.OPTV) 'Opp Past 12mo Target Value', 
  SUM(TEMPO.OFV) 'Opp Future 12mo Value', 
  SUM(TEMPO.OFTV) 'Opp Future 12mo Target Value',
  (SELECT TARGETAMOUNT_NORMALIZEDAMOUNT_CODE_NAME FROM APP_OPPORTUNITIES LIMIT 1) CURRENCY
FROM 
  (SELECT 
  CASE
    WHEN O.TARGETDATE < CURDATE() THEN O.AMOUNT_NORMALIZEDAMOUNT_AMOUNT
    ELSE 0
  END OPV,
  CASE
    WHEN O.TARGETDATE < CURDATE() THEN O.TARGETAMOUNT_NORMALIZEDAMOUNT_AMOUNT
    ELSE 0
  END OPTV,
  CASE
    WHEN O.TARGETDATE > CURDATE() THEN O.AMOUNT_NORMALIZEDAMOUNT_AMOUNT
    ELSE 0
  END OFV,
  CASE
    WHEN O.TARGETDATE > CURDATE() THEN O.TARGETAMOUNT_NORMALIZEDAMOUNT_AMOUNT
    ELSE 0
  END OFTV
  FROM 
  APP_OPPORTUNITIES O
  WHERE
    O.ISSUBORDINATE <> 'true'
    AND O.FLOWS_SALESSTAGES_STATE_NAME NOT IN ('transitioned', 'FLOWS_SALESSTAGES_STATE_NAME')
    AND O.TARGETDATE <= ADDDATE(CURDATE(), INTERVAL 1 YEAR)
    AND O.TARGETDATE >= SUBDATE(CURDATE(), INTERVAL 1 YEAR)
  ) TEMPO;
